[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 999999
solc_version = "0.8.15"

[fuzz]
runs = 12


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
